name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # unit-test:
  #   name: Unit tests
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [18.x]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'
  #     - run: npm i
  #     - run: npm run build
  #     - run: npm test

  # stack-tests:
  #   name: Stack tests
  #   runs-on: ubuntu-latest
  #   needs: unit-test

  #   strategy:
  #     matrix:
  #       node-version: [18.x]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'
  #     - run: npm i
  #     - run: npm run build
  #     - run: npm run -w=@sw-internal/stack-tests dev
  #       env:
  #         RELAY_HOST: ${{ secrets.RELAY_HOST }}
  #         RELAY_PROJECT: ${{ secrets.RELAY_PROJECT }}
  #         RELAY_TOKEN: ${{ secrets.RELAY_TOKEN }}

  # stage-e2e-realtime-api:
  #   name: E2E tests Realtime API - Staging
  #   runs-on: ubuntu-latest
  #   needs: stack-tests

  #   strategy:
  #     matrix:
  #       node-version: [18.x]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'
  #     - run: npm i
  #     - run: npm run build
  #     - run: npm run -w=@sw-internal/e2e-realtime-api dev
  #       env:
  #         SW_TEST_CONFIG: ${{ secrets.STAGING_E2E_REALTIME_SW_TEST_CONFIG }}

  # prod-e2e-realtime-api:
  #   name: E2E tests Realtime API - Production
  #   runs-on: ubuntu-latest
  #   needs: stack-tests

  #   strategy:
  #     matrix:
  #       node-version: [18.x]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'
  #     - run: npm i
  #     - run: npm run build
  #     - run: npm run -w=@sw-internal/e2e-realtime-api dev
  #       env:
  #         SW_TEST_CONFIG: ${{ secrets.PRODUCTION_E2E_REALTIME_SW_TEST_CONFIG }}

  stage-e2e-js:
    name: E2E tests JS - Staging
    runs-on: ubuntu-latest
    # needs: stack-tests

    strategy:
      matrix:
        node-version: [18.x]
        # project: [default, streaming, slow]
        project: [default, slow]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - run: npm run build
      - run: npm run -w=@sw-internal/e2e-js dev -- --project ${{ matrix.project }}
        env:
          SW_TEST_CONFIG: ${{ secrets.STAGING_E2E_JS_SW_TEST_CONFIG }}

  # prod-e2e-js:
  #   name: E2E tests JS - Production
  #   runs-on: ubuntu-latest
  #   needs: stack-tests

  #   strategy:
  #     matrix:
  #       node-version: [18.x]
  #       # project: [default, streaming, slow]
  #       project: [default, slow]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'
  #     - run: npm i # && npx playwright install-deps chromium
  #     - run: npm run build
  #     - run: npm run -w=@sw-internal/e2e-js dev -- --project ${{ matrix.project }}
  #       env:
  #         SW_TEST_CONFIG: ${{ secrets.PRODUCTION_E2E_JS_SW_TEST_CONFIG }}
